# Generated by Django 4.1.5 on 2023-02-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, verbose_name='Área de la vacante')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas_vacante',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del logo')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('visibiliy', models.BooleanField(default=False, verbose_name='Mostrar logo')),
                ('asignado', models.DateTimeField(auto_now_add=True, verbose_name='Asignado')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'db_table': 'Logos',
                'ordering': ['asignado'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carreras', models.TextField(verbose_name='Carrera afín')),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Hombre', 'Hombre')], max_length=20, verbose_name='Género')),
                ('experiencia', models.TextField(verbose_name='Experiencia')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Postulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('vacante', models.CharField(max_length=50, verbose_name='Vacante postulada')),
                ('postulado', models.DateTimeField(auto_now_add=True, verbose_name='Postulado:')),
            ],
            options={
                'verbose_name': 'Postulado',
                'verbose_name_plural': 'Postulados',
                'db_table': 'postulados',
                'ordering': ['postulado'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVacante', models.CharField(max_length=200, verbose_name='Nombre de la vacante')),
                ('nombreEmpresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('nivelVacante', models.CharField(max_length=200, verbose_name='Nivel de la vacante')),
                ('carreras_afinVacante', models.TextField(verbose_name='Carreras afines')),
                ('descripcion', models.TextField(verbose_name='Descripción breve de la vacante')),
                ('actividades', models.TextField(verbose_name='Actividades de la vacante')),
                ('sueldo', models.CharField(max_length=50, verbose_name='Sueldo de la vacante')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de la empresa')),
                ('genero', models.CharField(choices=[('Ambos', 'Ambos'), ('Femenino', 'Femenino'), ('Hombre', 'Hombre')], max_length=10, verbose_name='Género')),
                ('experiencia', models.TextField(verbose_name='Área de experiencia')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('visible', models.BooleanField(default=False, verbose_name='¿Disponible?')),
                ('horario', models.CharField(default=None, max_length=50, verbose_name='Horario')),
                ('nombreContacto', models.CharField(max_length=50, verbose_name='Nombre del contacto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacantes.area')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'db_table': 'vacante',
                'ordering': ['creado'],
            },
        ),
    ]
